#!/usr/bin/env python3
"""
============================================================================
 XELIS Vault v5.0 — Installer
============================================================================

Bootstraps the XELIS Vault miner / provider / keeper stack on a fresh
machine. 100% offline — no telemetry, no phone-home, no wallet info ever
leaves the local machine.

USAGE:
    python3 install.py                # install
    python3 install.py --uninstall    # remove

What it does:
    1. Verifies Python >= 3.10
    2. Creates a virtualenv at ~/.xelis-vault/venv
    3. Installs Python deps: requests, xelis-sdk (placeholder),
       python-dotenv
    4. Creates ~/.xelis-vault/ with subdirs logs/, config/, wallet/
    5. Copies scripts/custom_sources.example.json →
       ~/.xelis-vault/config/custom_sources.json
    6. Generates ~/.xelis-vault/config/.env with placeholders
    7. Generates ~/.xelis-vault/config/config.json with placeholders
    8. Prints next steps (register miner, start daemon)

PRIVACY:
    This installer does NOT collect telemetry, does NOT phone home, and
    does NOT transmit any wallet information anywhere. All operations are
    local to your machine.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

# ============================================================================
# CONFIGURATION
# ============================================================================
VAULT_DIR = Path.home() / ".xelis-vault"
VENV_DIR = VAULT_DIR / "venv"
LOGS_DIR = VAULT_DIR / "logs"
CONFIG_DIR = VAULT_DIR / "config"
WALLET_DIR = VAULT_DIR / "wallet"

# Where this installer lives — used to find sibling scripts/ and examples
REPO_ROOT = Path(__file__).resolve().parent
SCRIPTS_DIR = REPO_ROOT / "scripts"
EXAMPLE_SOURCES = SCRIPTS_DIR / "custom_sources.example.json"

# Python dependencies installed into the venv
PYTHON_DEPS = [
    "requests>=2.31",
    "python-dotenv>=1.0",
    # xelis-sdk is a placeholder for the official XELIS Python SDK
    # when it is released. Install manually from:
    #   pip install git+https://github.com/xelis-project/xelis-sdk-py
    "xelis-sdk>=0.0.1",
]

# Minimum Python version
MIN_PY = (3, 10)

# Placeholders written into the .env / config.json files. The user must
# edit them with their real values before starting the daemon.
ENV_TEMPLATE = """# XELIS Vault v5.0 — environment configuration
# Generated by install.py — EDIT THE PLACEHOLDERS before starting the daemon.

# --- Wallet ---
# Path to your xelis_wallet storage directory (created by `xelis_wallet create-wallet`)
WALLET_PATH={wallet_path}

# --- RPC ---
# XELIS daemon JSON-RPC URL (default: localhost:8080)
XELIS_RPC=http://127.0.0.1:8080

# --- Miner identity ---
# The XELIS address of your miner wallet (xet1...)
MINER_ADDRESS=xet1REPLACE_ME

# Public endpoint URL where users can reach your chat relayer.
# Leave empty ("") if you only run oracle.
ENDPOINT_URL=

# Services mask: 1=oracle, 2=chat, 3=both
SERVICES_MASK=1

# --- Contracts (from deployment.json on your network) ---
CONTRACT_REGISTRY=0xREPLACE_ME
VLT_TOKEN_CONTRACT=0xREPLACE_ME
XELIS_VAULT_MINER_CONTRACT=0xREPLACE_ME
STAKED_ORACLE_CONTRACT=0xREPLACE_ME
VAULT_CHAT_CONTRACT=0xREPLACE_ME
VLT_ASSET_HASH=0xREPLACE_ME

# --- Logging ---
LOG_LEVEL=INFO
PROMETHEUS_PORT=9091

# --- Privacy ---
# If true, wallet balances are masked with **** in logs. Keep this on.
MASK_BALANCES=true
"""

CONFIG_TEMPLATE = """{
  "wallet_path": "__WALLET_PATH__",
  "rpc_url": "http://127.0.0.1:8080",
  "miner_address": "xet1REPLACE_ME",
  "endpoint_url": "",
  "services_mask": 1,
  "contracts": {
    "ContractRegistry": "0xREPLACE_ME",
    "VLTToken": "0xREPLACE_ME",
    "XelisVaultMiner": "0xREPLACE_ME",
    "StakedOracle": "0xREPLACE_ME",
    "VaultChat": "0xREPLACE_ME"
  },
  "vlt_asset_hash": "0xREPLACE_ME",
  "log_level": "INFO",
  "log_dir": "__LOGS_DIR__",
  "prometheus_port": 9091,
  "mask_balances": true,
  "heartbeat_interval_blocks": 100,
  "reputation_warning_threshold": 5000,
  "reputation_critical_threshold": 1000
}
"""


# ============================================================================
# HELPERS
# ============================================================================
def info(msg: str) -> None:
    print(f"  [INFO]  {msg}")


def ok(msg: str) -> None:
    print(f"  [ OK ]  {msg}")


def warn(msg: str) -> None:
    print(f"  [WARN]  {msg}")


def err(msg: str) -> None:
    print(f"  [FAIL]  {msg}", file=sys.stderr)


def check_python_version() -> None:
    """Abort if Python is too old."""
    if sys.version_info < MIN_PY:
        err(f"Python {MIN_PY[0]}.{MIN_PY[1]}+ is required (you have "
            f"{sys.version_info.major}.{sys.version_info.minor}).")
        sys.exit(1)
    ok(f"Python {sys.version_info.major}.{sys.version_info.minor}."\
       f"{sys.version_info.micro} detected (>= {MIN_PY[0]}.{MIN_PY[1]})")


def create_dirs() -> None:
    """Create ~/.xelis-vault/{logs,config,wallet}."""
    for d in (VAULT_DIR, LOGS_DIR, CONFIG_DIR, WALLET_DIR):
        d.mkdir(parents=True, exist_ok=True)
    ok(f"Created directory tree at {VAULT_DIR}")


def create_venv() -> None:
    """Create a virtualenv at ~/.xelis-vault/venv if missing."""
    if VENV_DIR.exists():
        ok(f"Virtualenv already exists at {VENV_DIR} (skipping)")
        return
    info(f"Creating virtualenv at {VENV_DIR} ...")
    try:
        import venv
        venv.create(str(VENV_DIR), with_pip=True, clear=False)
        ok("Virtualenv created")
    except Exception as e:
        err(f"Failed to create virtualenv: {e}")
        sys.exit(1)


def venv_python() -> str:
    """Path to the venv's python executable."""
    if os.name == "nt":
        return str(VENV_DIR / "Scripts" / "python.exe")
    return str(VENV_DIR / "bin" / "python")


def install_deps() -> None:
    """pip install the Python deps into the venv."""
    info("Installing Python dependencies (this may take a minute) ...")
    cmd = [venv_python(), "-m", "pip", "install", "--upgrade",
           "pip", "wheel", "setuptools"]
    subprocess.run(cmd, check=True, capture_output=True)
    cmd = [venv_python(), "-m", "pip", "install"] + PYTHON_DEPS
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        # xelis-sdk is a placeholder — if pip can't find it, install the
        # rest and warn.
        if "xelis-sdk" in result.stderr:
            warn("xelis-sdk not yet published — install manually when "
                 "available. Continuing with the other deps.")
            cmd = [venv_python(), "-m", "pip", "install"] + [
                d for d in PYTHON_DEPS if not d.startswith("xelis-sdk")
            ]
            subprocess.run(cmd, check=True)
        else:
            err("pip install failed:")
            print(result.stderr, file=sys.stderr)
            sys.exit(1)
    ok("Dependencies installed: " + ", ".join(
        d.split(">=")[0].split("[")[0] for d in PYTHON_DEPS))


def copy_example_sources() -> None:
    """Copy scripts/custom_sources.example.json → config/custom_sources.json."""
    dest = CONFIG_DIR / "custom_sources.json"
    if dest.exists():
        ok(f"custom_sources.json already exists at {dest} (skipping)")
        return
    if not EXAMPLE_SOURCES.exists():
        warn(f"Example file missing: {EXAMPLE_SOURCES}")
        warn("Skipping custom_sources.json copy. Create it manually.")
        return
    shutil.copy2(EXAMPLE_SOURCES, dest)
    ok(f"Copied example → {dest}")


def write_env_file() -> None:
    """Write ~/.xelis-vault/config/.env with placeholders."""
    env_path = CONFIG_DIR / ".env"
    if env_path.exists():
        ok(f".env already exists at {env_path} (skipping)")
        return
    content = ENV_TEMPLATE.format(wallet_path=str(WALLET_DIR))
    env_path.write_text(content)
    # Restrict permissions on the env file (contains API keys later)
    try:
        env_path.chmod(0o600)
    except OSError:
        pass  # Windows
    ok(f"Wrote {env_path} (chmod 600)")


def write_config_json() -> None:
    """Write ~/.xelis-vault/config/config.json with placeholders."""
    cfg_path = CONFIG_DIR / "config.json"
    if cfg_path.exists():
        ok(f"config.json already exists at {cfg_path} (skipping)")
        return
    content = (CONFIG_TEMPLATE
               .replace("__WALLET_PATH__", str(WALLET_DIR))
               .replace("__LOGS_DIR__", str(LOGS_DIR)))
    cfg_path.write_text(content)
    ok(f"Wrote {cfg_path}")


def print_next_steps() -> None:
    """Print instructions for what to do after install."""
    print()
    print("=" * 70)
    print("  XELIS Vault v5.0 installation complete!")
    print("=" * 70)
    print()
    print("  Next steps:")
    print()
    print("  1. Edit your config:")
    print(f"       $EDITOR {CONFIG_DIR / '.env'}")
    print(f"       $EDITOR {CONFIG_DIR / 'config.json'}")
    print(f"       $EDITOR {CONFIG_DIR / 'custom_sources.json'}")
    print("     Replace all REPLACE_ME placeholders with your real values.")
    print()
    print("  2. Make sure your XELIS daemon is synced:")
    print("       xelis_daemon --network testnet --rpc-server &")
    print()
    print("  3. Create / open your XELIS wallet:")
    print("       xelis_wallet --network testnet --rpc-server &")
    print("       xelis_wallet --network testnet")
    print("       > create-wallet mywallet")
    print("       > get-address     # → xet1...")
    print()
    print("  4. Get 100 VLT (testnet faucet or mainnet VaultSwap).")
    print()
    print("  5. Register as a miner (entry ID 0 on XelisVaultMiner):")
    print("       xelis_wallet call-contract <XelisVaultMiner> register_miner \\")
    print("         --signer mywallet \\")
    print("         --deposit <VLT_ASSET_HASH> 10000000000 \\")
    print('         "https://your-miner.example.com:8080" \\')
    print("         0x<chat_pubkey_or_zero> \\")
    print("         1   # services_mask = oracle only")
    print()
    print("  6. Start the miner daemon:")
    print(f"       {venv_python()} {SCRIPTS_DIR / 'xelis_vault_miner.py'} \\")
    print(f"         --wallet {WALLET_DIR} \\")
    print("         --rpc http://localhost:8080")
    print()
    print("  7. (Optional) Start the price provider:")
    print(f"       {venv_python()} {SCRIPTS_DIR / 'price_provider.py'} --verbose")
    print()
    print("  8. (Optional) Start the aggregation keeper:")
    print(f"       {venv_python()} {SCRIPTS_DIR / 'aggregation_keeper.py'} "
          "--feed-ids 0 --interval 25")
    print()
    print("  See docs/MINER_GUIDE.md and docs/PROVIDER_GUIDE.md for details.")
    print()
    print("  PRIVACY: this installer collected NO telemetry and sent NO")
    print("  data anywhere. Your wallet info, API keys, and IP address")
    print("  never leave this machine.")
    print()
    print("=" * 70)


def uninstall() -> None:
    """Remove ~/.xelis-vault entirely."""
    if not VAULT_DIR.exists():
        ok(f"Nothing to uninstall — {VAULT_DIR} does not exist")
        return
    print(f"This will remove {VAULT_DIR} (venv, config, logs, wallet).")
    print("Are you sure? Type 'yes' to confirm:")
    try:
        reply = input("> ").strip().lower()
    except EOFError:
        reply = ""
    if reply != "yes":
        ok("Uninstall cancelled")
        return
    shutil.rmtree(VAULT_DIR)
    ok(f"Removed {VAULT_DIR}")
    print()
    print("Note: your XELIS wallet (if stored elsewhere) and on-chain")
    print("registrations are not affected. To deregister your miner, run:")
    print("  xelis_wallet call-contract <XelisVaultMiner> deregister_miner "
          "--signer mywallet")


# ============================================================================
# MAIN
# ============================================================================
def install() -> None:
    print()
    print("=" * 70)
    print("  XELIS Vault v5.0 — Installer")
    print("=" * 70)
    print()
    print("  PRIVACY: this installer does NOT collect telemetry, does NOT")
    print("  phone home, and does NOT transmit any wallet info. All ops")
    print("  are local to your machine.")
    print()

    check_python_version()
    create_dirs()
    create_venv()
    install_deps()
    copy_example_sources()
    write_env_file()
    write_config_json()
    print_next_steps()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="XELIS Vault v5.0 installer (offline, no telemetry)"
    )
    parser.add_argument(
        "--uninstall", action="store_true",
        help="Remove ~/.xelis-vault entirely (venv, config, logs, wallet)"
    )
    args = parser.parse_args()

    if args.uninstall:
        uninstall()
    else:
        install()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nInterrupted by user")
        sys.exit(1)
